### PR TITLE
Updating hyphenation characters (issue #6)

### PR DESCRIPTION
**Pull request by typiconman**
I updated the hyphenation character widths and repositioned the underscore, as requested in #6. I also added two characters to the PUA: U+EC4C Three-Quarters Hyphen and U+EC4D Half Hyphen. They could be used for something down the road. Finally, because I have not yet been able to figure out if a hyphenation character can be explicitly set in LO, I have added a Graphite feature _hyph_ that, when enabled, replaced the shape of the hyphen with an underscore.

@starover77, @pgmmpk, please comment.

Binaries for easy testing:
[PonomarUnicode-1.2.zip](https://github.com/typiconman/fonts-cu/files/201299/PonomarUnicode-1.2.zip)

### CODE REVIEW

**Comment by pgmmpk** [comment]
image

Thank you, looks much better now!

**Comment by typiconman** [comment]
@starover77 Please express your opinion.

**Comment by starover77** [comment]
I guess it looks good to me, but to be honest, I really don't have a strong idea of what looks right or authentic for Nikonian era texts. I have spent my whole life working with pre-Nikonian texts, which as you know do not use hyphenation (although we do use word-division based on the splitting of word roots, prefixes and suffixes, and not on the modern western basis of splitting a word according to its syllables).

**Comment by typiconman** [comment]
OK. Have a safe trip!

**Pull request merged**
