### PR TITLE
Modifying ASCII digits

### PR DESCRIPTION
**Pull request by typiconman**
@starover77 Please take a look at the changes to the ASCII digits. If you think this is OK, I will go ahead and commit this. The work is currently in a different branch.
digits

### CODE REVIEW

**Comment by mamyt** [comment]
In my opinion, the numbers are too thin compared with the surrounding text.
This is especially a problem when the numbers are immediately followed by a
hyphen/underscore and further text. Separated by white space this is less
of an issue, but it is still clear that the numbers are somehow “special or
different.”

**Comment by typiconman** [comment]
Well I made the digits the same metric as the Latin characters. But yes
they are narrower than the Cyrillic characters. I do not know if this is a
problem. Most of the time you will use Cyrillic numerals with Slavonic text.

**Comment by mamyt** [comment]
This is a problem when we mix styles within a single font. It becomes
difficult to effectively display components, such as numbers and
punctuation, in both styles correctly.  Would it not be possible to have
the programme automatically select thicker variants when the script is set
to Cyrillic or the text surrounding the letters is thicker?

**Comment by typiconman** [comment]
We've got the "blackletter" glyphs in Stylistic Set 2, but the proposal was to get rid of the blackletter glyphs and replace them with normal roman glyphs. We could create a localized rule that forces use of the blackletter glyphs whenever the language is Church Slavonic, but then I fail to see the point of this change. 
Mostly, I think one would use the roman glyphs for things like page numbering, where blackletter glyphs are not really desired.

**Comment by typiconman** [comment]
Sorry, I hit the wrong button.

**Comment by mamyt** [comment]
But I fail to see the point of doing that in the Ponomar font. The Roman
glyphs do not match the character of the Cyrillic letters and so we
essentially have a mixed font, which is not necessarily stylistically
pleasing. I am not exactly sure why we want such a mixed font. If I wish to
use proper Roman letters, then I will use a corresponding font, such as
Time New Roman. As well, what about the punctuation? How will it work with
the normal Roman glyphs?

The other question is why can we not use another font for the page
numbering when we need as a proper Roman form? Are we trying to avoid some
sort of limitations with some software?

**Comment by typiconman** [comment]
@mamyt: I agree that it is weird, but we need to provide Latin characters in the font. The question is what style of Latin characters to provide. Are you proposing to keep the Blackletter glyphs for the numerals? Please look at the attached. 
digits

**Comment by typiconman** [comment]
XB! 
Here is a better illustration of what I am proposing.
digits

**Comment by mamyt** [comment]
XB!

I think that the Blackletter matches better the overall feel and format of
the Cyrillic letters. As the well, the location of the superscript is
better in the Blackletter case is better than for the Normal case (but I
presume that this could easily be fixed).

Are there any examples where we would need to use only this font and would
require “Normal” Latin letters? If not, I think that we should keep the
Latin letters as Blackletter and if we need normal Latin letters we can
switch the font. I still feel that a single font should have a coherent
overall feel to it (even the different styles should still work well with
each other).

**Comment by typiconman** [comment]
BB!
Having the Latin characters in Blackletter as a default is annoying. Which is why it seems the best solution is to have the two style sets: if you need blackletter, you just turn on ss02, and everything becomes blackletter -- letters and numerals. I'll go ahead and merge this, and then we can open up a separate issue to fix Latin superscript positioning and kerning.

**Comment by starover77** [comment]
Christ is risen!

I approve of the course of action that Aleksandr proposes, as it would allow both choices.

**Pull request merged**
