### PR TITLE
Adding Cyrillic localized forms (issue #2)

### PR DESCRIPTION
**Pull request by typiconman**
Fixing issue #2 
@mamyt I think you requested this feature; please check. In addition to Ukrainian and Byelorussian, I added the dotted Cyrillic i for Kazakh, Khakas, Komi, and Rusyn.

### CODE REVIEW

**Comment by typiconman** [comment]
I forgot about the soft dot property for the Cyrillic i and j. Added rules that remove the dot when i or j takes a diacritic.

**Comment by mamyt** [comment]
Yes. I did mention this issue. I do not think that the Cyrillic “j” can
ever take a diacritical mark (as it is equivalent in the Serbian Cyrillic
to the East Slavonic й). I do not think that there are any other localised
forms that we would need to consider. I will have a brief look at this
issue in the next few days and let you know if we need any other localised
forms.

**Comment by typiconman** [comment]
Hm, if j can never take an accent, then maybe I made the problem too complicated.

**Comment by mamyt** [comment]
I agree.

**Comment by mamyt** [comment]
We also need to add a localised form for capital Ukrainian Ye (Є), since in
Ukrainian the capital form should not be the same as the capital form of Е
(as they are very distinct letters). I would suggest taking the lowercase є
and making it larger. Otherwise, I cannot think of any other localised
forms that we would need for our font.

**Comment by typiconman** [comment]
@mamyt How would you feel about a flipped version of the current glyph at U+042D for the Ukrainian Ye?

**Comment by mamyt** [comment]
That would do.

**Comment by typiconman** [comment]
@mamyt Please take a look at the updated version. Sample:
test

**Comment by mamyt** [comment]
Looks good to me. Could you try it with the words “Єнот Єдність Є НАДІЄ
ГОСПОДНЄ МОЄ Б’ЄШ ЗНАЄ” to see how it looks in actual Ukrainian words?
Thanks.

**Comment by typiconman** [comment]
@mamyt Looks like the attached.
unitlted

**Comment by typiconman** [comment]
@mamyt Any further comments or can I close this issue?

**Comment by mamyt** [comment]
You can close it. I am fine with the result.

**Comment by typiconman** [comment]
@KrasnayaPloshchad : I added the two serifs. Please take a look, and if you like it, I will also add them to U+042D. (I pushed straight to master since this is a simple fix.)

**Comment by KrasnayaPloshchad** [comment]
OK, it’s good, U+042D can also having serifs.

**Comment by typiconman** [comment]
@KrasnayaPloshchad I added serifs to U+042D, please check.

**Comment by KrasnayaPloshchad** [comment]
OK, it’s fine

**Comment by KrasnayaPloshchad** [comment]
> We also need to add a localised form for capital Ukrainian Ye (Є), since in Ukrainian the capital form should not be the same as the capital form of Е (as they are very distinct letters). I would suggest taking the lowercase є and making it larger. Otherwise, I cannot think of any other localised forms that we would need for our font.

This variant should also available for Rusyn texts, I think.

**Comment by mamyt** [comment]
You are correct. It also  needs to be available for Rusyn texts, ISO code:
“rue”.

**Pull request merged**
