### PR TITLE
Adding Makefile and refactoring directory structure

### PR DESCRIPTION
**Pull request by typiconman**
@pgmmpk: Please check my Makefile. This is supposed to create the package for CTAN.

### CODE REVIEW

**Comment by typiconman** [comment]
Also, do we need something to make `tlmgr` work? Or it knows where to copy the font files?

**Comment by pgmmpk** [comment]
We just need to upload this to CTAN. Then CTAN maintainers will check and decide where in the TeX tree to put this. TeXLive maintainers will pick it from CTAN and do what is needed (basically, create tlmrg control file so that tlmgr knows that this package exists).

**Comment by pgmmpk** [comment]
Looks good. Could you please merge this and send me the ZIP. I will upload it to CTAN.

**Comment by typiconman** [comment]
OK. However, I'd like to change the shape of the ASCII digits before we release this and provide serif digits instead of the blackletter ones (we'll move the blackletter digits to SS02). Please see https://github.com/typiconman/fonts-cu/pull/14. Let's give @starover77 a day to review this.

**Pull request merged**
