### PR TITLE
Ponomar Unicode. Contour revisions

### PR DESCRIPTION
**Pull request by StefanPeev**
I offer revisions of the contours so that they to be in compliance with the typographic requirements for better contours. See the pictures below.

PonomarUnicode_01

PonomarUnicode_02

### CODE REVIEW

**Comment by typiconman** [comment]
What is in the binary vfc file?

**Comment by StefanPeev** [comment]
VFC is the default format for FontLab 8. I work on FontLab 8 but at the end of the process I transform the file to SFD for FontForge.

**Comment by StefanPeev** [comment]
The new SFD file is PonomarUnicode-Regular.sfd v.1.004.

**Comment by StefanPeev** [comment]
OK. I deleted the VFC file from my branch "local". I'll close this pull request and will open another one without the VFC file.

**Pull request closed without merging**
